apiVersion: v1
kind: ConfigMap
metadata:
  name: tenants-blackbox-config
data:
  blackbox.yml: |
    modules:
      tenants_health:
        prober: http
        timeout: 5s
        http:
          method: GET
          preferred_ip_protocol: "ip4"
